app:
    resource: "@AppBundle/Controller/"
    type:     annotation

app_hello_world:
    path: /hello/{name}
    defaults:
        _controller: 'AppBundle:Default:hello'
        name: world
    requirements:
        name: '[a-z]+'
    methods: [GET]