# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    role_hierarchy:
        ROLE_USER_VIP:  ROLE_USER
        ROLE_ADMIN: [ROLE_USER_VIP, ROLE_ALLOWED_TO_SWITCH]

    encoders:
        AppBundle\Entity\UserAccount: bcrypt

    providers:
        users:
            chain:
                providers: [users_by_nickname, users_by_email]
        users_by_nickname:
            entity: { class: 'AppBundle:UserAccount', property: nickname }
        users_by_email:
            entity: { class: 'AppBundle:UserAccount', property: emailAddress }


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern: ^/admin
            provider: users
            http_basic: ~

        main:
            pattern: ^/
            provider: users
            anonymous: ~
            switch_user: ~
            form_login:
                login_path: app_login
                check_path: app_login_check
                default_target_path: app_game_play
                always_use_default_target_path: true
                username_parameter: my_login
                password_parameter: my_secret
            logout:
                path: app_logout
                target: app_login


