# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:

    app.game_runner:
        class: 'AppBundle\Game\GameRunner'
        arguments: ['@app.game_context', '@?app.word_list']


    app.word_list:
        class: 'AppBundle\Game\WordList'
        calls:
            - [ 'addWord', [ 'computer' ] ]
            - [ 'addWord', [ 'monitors' ] ]
            - [ 'addWord', [ 'cellular' ] ]

    app.game_context:
        class: 'AppBundle\Game\GameContext'
        arguments: ['@session']



